# Numpy_Assignment_2::

## Question:1

### Convert a 1D array to a 2D array with 2 rows?

In [97]:
import numpy as np 

#### Desired output::

array([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [101]:
a1 = np.array([0,1,2,3,4,5,6,7,8,9])
a1.reshape((2,5))

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

## Question:2

###  How to stack two arrays vertically?

#### Desired Output::

In [102]:
a = np.array([1,2,3,4,5,6,7])
b = np.array([8,9,10,11,12,13,14])
a, b
np.vstack((a, b))

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14]])

## Question:3

### How to stack two arrays horizontally?

#### Desired Output::

In [103]:
np.hstack((a,b))

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

## Question:4

### How to convert an array of arrays into a flat 1d array?

#### Desired Output::

In [104]:
a = np.array([[1,2,3,4,5], [6,7,8,9,10]])
a.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

## Question:5

### How to Convert higher dimension into one dimension?

#### Desired Output::

In [105]:
arr1 = np.arange(9)
arr1

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [106]:
arr1.shape

(9,)

In [107]:
arr2 = arr1.reshape((3,3))
arr2

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [108]:
arr2.reshape((9,))

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

## Question:6

### Convert one dimension to higher dimension?

#### Desired Output::

In [109]:
arr1

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [110]:
arr1.reshape((3,3))

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

## Question:7

### Create 5x5 an array and find the square of an array?

In [111]:
sqrt1 = np.arange(25)
sqrt1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [112]:
sqrt1.reshape((5,5))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [113]:
np.sqrt(sqrt1)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766, 3.31662479, 3.46410162, 3.60555128, 3.74165739,
       3.87298335, 4.        , 4.12310563, 4.24264069, 4.35889894,
       4.47213595, 4.58257569, 4.69041576, 4.79583152, 4.89897949])

## Question:8

### Create 5x6 an array and find the mean?

In [114]:
arr3 = np.arange(30)
arr3

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [115]:
np.mean(arr3)

14.5

## Question:9

### Find the standard deviation of the previous array in Q8?

In [116]:
np.std(arr3)

8.65544144839919

## Question:10

### Find the median of the previous array in Q8?

In [117]:
np.median(arr3)

14.5

## Question:11

### Find the transpose of the previous array in Q8?

In [118]:
arr3.reshape((5,6))

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [119]:
np.transpose(arr3)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

## Question:12

### Create a 4x4 an array and find the sum of diagonal elements?

In [120]:
arr4 = np.array([[1,2,3,4], [5,6,7,8]])
arr4

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [121]:
np.diagonal(arr4)

array([1, 6])

## Question:13

### Find the determinant of the previous array in Q12?

In [126]:
arr4 = np.array([[1,2], [3,4]])
arr4

array([[1, 2],
       [3, 4]])

In [127]:
np.linalg.det(arr4)

-2.0000000000000004

## Question:14

### Find the 5th and 95th percentile of an array?

In [128]:
p = np.array([0,1,2,3,4,5,6,8,9,10,11,12,13,14,15,16,17,18,19,20])
p

array([ 0,  1,  2,  3,  4,  5,  6,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [129]:
np.percentile(p, 5)

0.9500000000000001

In [130]:
np.percentile(p, 95)

19.05

## Question:15

### How to find if a given array has any null values?

In [132]:
ar3 = np.arange(16)
ar3

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [136]:
np.isnan(ar3)

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False])